version: '3.8'

services:
  mqtt-broker:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto_tp
    restart: always
    ports:
      - "1883:1883"
      - "8883:8883"
      - "9001:9001"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./config/passwd:/etc/mosquitto/passwd:ro
      - ./config/aclfile:/etc/mosquitto/aclfile:ro
      - ./certs:/etc/mosquitto/certs:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

volumes:
  mosquitto_data:
  mosquitto_log:
